version: '3'
services:
  docker-registry:
    image: registry:2.3.0
    ports: ["5000:5000"]
    volumes:
      - $PWD/docker-registry:/var/lib/registry


  docker-registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports: ["5001:80"]
    environment:
    - ENV_DOCKER_REGISTRY_HOST=docker-registry
    - ENV_DOCKER_REGISTRY_PORT=5000
    - ENV_MODE_BROWSE_ONLY=true

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports: ["80:80"]
    volumes:
      - '/gitlab/config:/etc/gitlab'
      - '/gitlab/logs:/var/log/gitlab'
      - '/gitlab/data:/var/opt/gitlab'